# Generated by Django 5.0.4 on 2025-06-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produittaille',
            name='produit',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tailles', to='store.produit'),
            preserve_default=False,
        ),
    ]
