# Generated by Django 5.0.4 on 2025-06-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_produittaille_produit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produittaille',
            name='produit',
        ),
    ]
