# Generated by Django 5.0.4 on 2025-06-25 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_produittaille_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitcouleur',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produitpanier',
            name='couleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.produitcouleur'),
        ),
    ]
