# Generated by Django 5.0.4 on 2025-06-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_produitcouleur_couleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitpanier',
            name='taille',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
