# Generated by Django 5.0.4 on 2025-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_produitpanier_taille'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produittaille',
            name='produit',
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produittaille',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produittaille',
            name='taille',
            field=models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41')], max_length=5),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='prix_bureau',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='prix_domicile',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
