# Generated by Django 5.0.4 on 2025-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_produittaille_produit_alter_client_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total_avec_livraison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='total_sans_livraison',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='type_livraison',
            field=models.CharField(choices=[('bureau', 'توصيل للمكتب'), ('a domicile', 'توصيل للمنزل')], max_length=10),
        ),
        migrations.AlterField(
            model_name='produittaille',
            name='taille',
            field=models.CharField(choices=[('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5),
        ),
    ]
