# Generated by Django 5.0.4 on 2025-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_commande_total_avec_livraison_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en attente', '⏳ En attente'), ('confirmé', '✅ Confirmé'), ('en livraison', '🚚 En livraison'), ('livré', '📦 Livré'), ('retour', '↩️ Retour'), ('retournée', '🔄 Retournée')], default='en attente', max_length=20),
        ),
    ]
