# Generated by Django 5.0.4 on 2025-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='vues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en attente', '⏳ En Attente'), ('confirmé', '✅ Confirmé'), ('en livraison', '🚚 En livraison'), ('livré', '📦 Livré'), ('retour', '↩️ Retour'), ('retournée', '🔄 Retournée')], default='en attente', max_length=20),
        ),
    ]
