# Generated by Django 5.0.4 on 2025-07-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_produit_vues_alter_commande_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visiteurs', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
