# Generated by Django 5.0.4 on 2025-09-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_produit_prix_promo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etiquette',
            field=models.CharField(blank=True, choices=[('nouveau', 'nouveau'), ('Promo', 'Promo'), ('Solde', 'Solde'), ('Bientot', 'Bientot'), ('', 'sans')], default='', max_length=20),
        ),
    ]
