# Generated by Django 5.0.4 on 2025-09-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_produit_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='produittaille',
            name='stock_vrai',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(max_length=100, verbose_name='descrption'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etiquette',
            field=models.CharField(blank=True, choices=[('Nouveau', 'Nouveau'), ('Promo', 'Promo'), ('Promo 30%', 'Promo 30%'), ('Solde', 'Solde'), ('Bientot', 'Bientot'), ('', 'sans')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='nom',
            field=models.CharField(max_length=100, verbose_name="nom de l'article"),
        ),
    ]
