# Generated by Django 5.0.4 on 2025-10-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_produittaille_stock_vrai_alter_produit_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='الاسم')),
                ('telephone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='etiquette',
            field=models.CharField(blank=True, choices=[('NOUVEAU', 'NOUVEAU'), ('PROMO', 'PROMO'), ('PROMO 30%', 'PROMO 30%'), ('SOLDE', 'SOLDE'), ('BIENTÔT ', 'BIENTÔT '), ('', 'sans')], default='', max_length=20),
        ),
    ]
