# Generated by Django 5.0.4 on 2025-10-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_messagecontact_alter_produit_etiquette'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='source',
            field=models.CharField(choices=[('site', 'الموقع'), ('messages_site', 'رسائل الموقع'), ('facebook', 'رسائل فيسبوك')], default='site', max_length=20, verbose_name='مصدر الطلبية'),
        ),
    ]
