# Generated by Django 5.0.4 on 2025-10-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_commande_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='source',
            field=models.CharField(choices=[('site', 'Sponsor_Site'), ('messages_site', 'Sponsor_Message'), ('facebook', 'Message')], default='site', max_length=20, verbose_name='مصدر الطلبية'),
        ),
    ]
