# Generated by Django 5.0.4 on 2025-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_commande_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_dachat',
            field=models.DecimalField(decimal_places=0, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
