# Generated by Django 5.0.4 on 2025-10-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_produit_prix_dachat_produit_prix_vente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='prix_dachat',
            new_name='prix_achat',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='prix_vente',
        ),
    ]
