# Generated by Django 5.0.4 on 2025-10-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_prix_dachat_produit_prix_achat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficeMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20, unique=True, verbose_name='الشهر')),
                ('total_benefice', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مجموع الفائدة')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'الفائدة الشهرية',
                'verbose_name_plural': 'الفوائد الشهرية',
            },
        ),
    ]
