# Generated by Django 5.0.4 on 2025-10-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_beneficemensuel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetourMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('total_retour', models.PositiveIntegerField(default=0, verbose_name='الطلبات المرتجعة')),
                ('total_retournee', models.PositiveIntegerField(default=0, verbose_name='الطلبات المسترجعة')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'المرتجعات الشهرية',
                'verbose_name_plural': 'المرتجعات الشهرية',
            },
        ),
    ]
