# Generated by Django 5.0.4 on 2025-10-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_retourmensuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock_restante',
            field=models.PositiveIntegerField(default=0, verbose_name='الكمية المتبقية'),
        ),
        migrations.AlterField(
            model_name='retourmensuel',
            name='total_retour',
            field=models.PositiveIntegerField(default=0, verbose_name='Commande  en retour'),
        ),
        migrations.AlterField(
            model_name='retourmensuel',
            name='total_retournee',
            field=models.PositiveIntegerField(default=0, verbose_name='Commande retournée'),
        ),
    ]
