# Generated by Django 5.0.4 on 2025-10-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_produit_stock_restante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produittaille',
            name='stock_initial',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
