# Generated by Django 5.0.4 on 2025-10-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_produittaille_stock_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpanier',
            name='stock_deduit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produitpanier',
            name='stock_vrai_deduit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='stock_restante',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock aprés livré'),
        ),
    ]
