# Generated by Django 5.0.4 on 2025-10-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_produitpanier_stock_deduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.panier'),
        ),
    ]
