# Generated by Django 5.0.4 on 2025-10-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_commande_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='produitpanier',
            name='stock_restitue',
            field=models.BooleanField(default=False),
        ),
    ]
