# Generated by Django 5.0.4 on 2025-10-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_produitpanier_stock_restitue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produitpanier',
            name='stock_deduit',
        ),
        migrations.RemoveField(
            model_name='produitpanier',
            name='stock_restitue',
        ),
        migrations.RemoveField(
            model_name='produitpanier',
            name='stock_vrai_deduit',
        ),
    ]
