# Generated by Django 5.0.4 on 2025-10-28 20:05

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_produitpanier_stock_deduit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
