# Generated by Django 5.0.4 on 2025-11-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_produitimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name=' المصروف')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ (DA)')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('type', models.CharField(choices=[('achter_article', 'achter_article'), ('sponsor', 'sponsor'), ('emballage', 'emballage'), ('autre', 'autre')], default='', max_length=20, verbose_name='نوع ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'المصاريف',
                'verbose_name_plural': 'المصاريف ',
                'ordering': ['-date'],
            },
        ),
    ]
